version: "3.8"

services:
    #Laravel App
    app:
        build:
            context: .
            target: php
            dockerfile: Dockerfile
        image: laravel-app
        container_name: laravel-app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - laravel

    # Nginx Service
    webserver:
        image: nginx:alpine
        container_name: laravel-webserver
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./docker/nginx:/etc/nginx/conf.d/
        networks:
            - laravel

    # MySQL Service
    db:
        image: mysql:5.7
        container_name: laravel-db
        ports:
            - "3307:3306"
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel

    # phpMyAdmin Service
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: laravel-phpmyadmin
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        ports:
            - "8081:80"
        networks:
            - laravel

volumes:
    dbdata: ~

networks:
    laravel:
